stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - build/

build-msvc:
  stage: build
  tags:
    - msvc
    - vcpkg
    - cmake
  script:
    - cmake --preset default
    - cmake --build build/ --target ALL_BUILD --parallel
