name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build-msvc:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: "x64-windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v10
      - name: build
        run: |
          cmake -B build/ -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=".\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --target ALL_BUILD --parallel
