name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build-msvc:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: "x64-windows-static"
      VCPKG_OVERLAY_TRIPLETS: "$(pwd)/triplets"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v10
      - name: build
        run: |
          cmake --preset default
          cmake --build build/ --target ALL_BUILD --parallel
